const i = {
	addRoles: true,
	addUsers: true,
	addPatients: true,
	addStudies: true,
	addOrders: true,
	editRoles: true,
	editUsers: true,
	editPatients: true,
	editStudies: true,
	editOrders: true,
	showAll: true,
	showPending: true,
	showVerified: true,
	showPrinted: true,
	showDelivered: true,
	showAssigned: true,
	editAll: true,
	editPending: true,
	editVerified: true,
	editPrinted: true,
	editDelivered: true,
	editAssigned: true,
};
